# Generated by Django 3.0.6 on 2020-05-25 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miembro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol_miembro',
            options={'verbose_name': 'Rol miembro', 'verbose_name_plural': 'Roles miembro'},
        ),
        migrations.AlterModelOptions(
            name='tipo_sangre',
            options={'verbose_name': 'Tipo de sangre', 'verbose_name_plural': 'Tipos de sangre'},
        ),
        migrations.AlterField(
            model_name='miembro',
            name='correo_institucional',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Correo electrónico institucional'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='correo_personal',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Correo electrónico personal'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rol_miembro',
            name='descripcion',
            field=models.CharField(help_text='Descripción del rol del miembro dentro de la rama', max_length=45, unique=True, verbose_name='Descripción rol'),
        ),
    ]
