# Generated by Django 3.0.6 on 2020-05-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembro', '0002_auto_20200525_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrio',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='ciudad',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='eps',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='miembro',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='rol_miembro',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='sede',
            old_name='estado',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='tipo_sangre',
            old_name='estado',
            new_name='activo',
        ),
    ]
