# Generated by Django 3.0.6 on 2020-05-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del tipo de actividad', max_length=45, unique=True, verbose_name='Descripción tipo actividad')),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
            },
        ),
        migrations.CreateModel(
            name='Actividad_interna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('nombre', models.CharField(help_text='Nombre de la actividad', max_length=255, verbose_name='Nombre actividad')),
                ('descripcion', models.TextField(help_text='Descripción de la actividad', verbose_name='Descripción de la actividad')),
                ('fecha_actividad', models.DateTimeField()),
                ('lugar_actividad', models.TextField(max_length=255)),
                ('solo_miembros', models.BooleanField(default=False)),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividad_interna.Tipo_actividad')),
            ],
            options={
                'verbose_name': 'Actividad interna',
                'verbose_name_plural': 'Actividades internas',
            },
        ),
    ]
